//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFCApplication1.rc
//
#define VERSION_MINOR                   0
#define VERSION_MAJOR                   1
#define IDR_RichEditDocTestTYPE_CNTR_IP 7
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_XML_DATA                    101
#define IDS_THREADS_TAB                 102
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MAINFRAME1                  129
#define IDR_MFCApplication1TYPE         130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_COMPILE                      138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDI_THREAD_RUNNING              169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG1                     310
#define IDR_MFCAPPLICATION1             311
#define IDR_HTML1                       312
#define IDR_HTML2                       313
#define IDR_TOOLBAR1                    314
#define IDB_BITMAP1                     315
#define IDB_BREAKPOINTS                 316
#define IDB_TREE_MARKERS                318
#define IDD_TAB_DLG                     319
#define IDR_POPUP_BREAKPOINTS           321
#define IDR_POPUP_VARLIST               322
#define IDB_PNG_BP_DISABLED             327
#define IDB_PNG_BP_ENABLED              328
#define IDB_MARKERS                     329
#define IDC_VERSION                     1000
#define IDC_MFCLINK1                    1001
#define IDC_WEB_LINK                    1001
#define ID_DEBUG_RUN                    32771
#define ID_DEBUG_STOP                   32772
#define ID_DEBUG_PAUSE                  32773
#define ID_DEBUG_STEPIN                 32774
#define ID_DEBUG_STEPOVER               32775
#define ID_DEBUG_STEPOUT                32776
#define ID_DEBUG_RUN32777               32777
#define ID_DEBUG_STOP32778              32778
#define ID_DEBUG_PAUSE32779             32779
#define ID_DEBUG_STEPIN32780            32780
#define ID_DEBUG_STEPOVER32781          32781
#define ID_DEBUG_STEPOUT32782           32782
#define ID_BUTTON32783                  32783
#define ID_SET_STARTUP_SCRIPT           32784
#define ID_Menu                         32785
#define ID_CLEAR_STARTUP_SCRIPT         32786
#define ID_Menu32787                    32787
#define ID_DECOMPILE                    32788
#define ID_Menu32789                    32789
#define ID_RUN                          32790
#define ID_DEBUG_DUMPMEMORY             32791
#define ID_DEBUG_DUMPMEMORY32792        32792
#define ID_WINDOW_ADDTAB                32793
#define ID_WINDOW_REMOVETAB             32794
#define ID_DELETE_DELETE                32802
#define ID_DELETE_BREAKPOINT            32803
#define ID_POPUP_VIEWASHEX              32804
#define ID_POPUP_VIEWASBINARY           32805
#define ID_POPUP_VIEWASDEFAULT          32806
#define ID_POPUP_VIEWADDRESS            32807
#define ID_POPUP_COPY                   32808
#define IDS_STACK_TAB                   61204
#define IDS_LOCAL_VARS_TAB              61205
#define IDS_GLOBAL_VARS_TAB             61206
#define IDS_BREAKPOINTS                 61207
#define IDS_WATCH_TAB                   61208

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        330
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           321
#endif
#endif
